### ISSUE TITLE
deleted vms should not be indefinitly exposed by the exporter

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/prometheus-iaas-tenant-exporter-boshrelease#2]
The exporter main use is to give current active VMs list to prometheus.
Current mechanism (Spring actuator metrics / prometheus exposition) is designed for static metrics / timeseries.
A vm metrics is exposed as a time serie, kept in memory.These timeseries are exposed for the JVM lifetime, even if the vms is deleted.
Should find a way to expire time serie or change design to not keep exporting deleted vm timeseries

/cc @szaouam  @shoudusse

**Comment by poblin-orange** [comment]
probably shoud use a pushgateway instead of raw spring boot metrics exposure

**Comment by obeyler** [comment]
Close with the new  version of prometheus iaas tenant exporter. 
This version includes a mechanism to evict vm witch were not reported by iaas anymore.
For vCloud api it has been bumped to 5.5 version
